/**
 * Message-related enumerations.
 */

/**
 * The type of a message.
 *
 * @remarks
 * Only `Default` and `Reply` are user-authored text; the rest are system messages
 * generated by Discord. A bot filtering for "real" messages usually wants those two.
 */
export const MessageType = {
  /** A normal message. */
  Default: 0,
  /** A user was added to a group DM. */
  RecipientAdd: 1,
  /** A user was removed from a group DM. */
  RecipientRemove: 2,
  /** A call was started. */
  Call: 3,
  /** A group DM name changed. */
  ChannelNameChange: 4,
  /** A group DM icon changed. */
  ChannelIconChange: 5,
  /** A message was pinned. */
  ChannelPinnedMessage: 6,
  /** A member joined the guild. */
  UserJoin: 7,
  /** A member boosted the guild. */
  GuildBoost: 8,
  /** A boost took the guild to tier 1. */
  GuildBoostTier1: 9,
  /** A boost took the guild to tier 2. */
  GuildBoostTier2: 10,
  /** A boost took the guild to tier 3. */
  GuildBoostTier3: 11,
  /** A channel was followed. */
  ChannelFollowAdd: 12,
  /** The guild was disqualified from Server Discovery. */
  GuildDiscoveryDisqualified: 14,
  /** The guild requalified for Server Discovery. */
  GuildDiscoveryRequalified: 15,
  /** Initial warning about Server Discovery requirements. */
  GuildDiscoveryGracePeriodInitialWarning: 16,
  /** Final warning about Server Discovery requirements. */
  GuildDiscoveryGracePeriodFinalWarning: 17,
  /** A thread was created. */
  ThreadCreated: 18,
  /** A reply to another message. */
  Reply: 19,
  /** A chat input (slash) command was used. */
  ChatInputCommand: 20,
  /** The first message in a thread, mirroring its parent. */
  ThreadStarterMessage: 21,
  /** A reminder to invite people to the guild. */
  GuildInviteReminder: 22,
  /** A context menu command was used. */
  ContextMenuCommand: 23,
  /** An AutoMod rule took action. */
  AutoModerationAction: 24,
  /** A role subscription was purchased. */
  RoleSubscriptionPurchase: 25,
  /** An interaction was premium-gated. */
  InteractionPremiumUpsell: 26,
  /** A stage instance started. */
  StageStart: 27,
  /** A stage instance ended. */
  StageEnd: 28,
  /** A user became a stage speaker. */
  StageSpeaker: 29,
  /** A stage instance topic changed. */
  StageTopic: 31,
  /** An application premium subscription was purchased. */
  GuildApplicationPremiumSubscription: 32,
  /** A poll finished. */
  PollResult: 46,
} as const

/**
 * A message type.
 */
export type MessageType = (typeof MessageType)[keyof typeof MessageType]

/**
 * Flags on a message.
 */
export const MessageFlags = {
  /** The message has been published to following channels. */
  Crossposted: 1 << 0,
  /** The message originated from another channel. */
  IsCrosspost: 1 << 1,
  /** Do not render this message's embeds. */
  SuppressEmbeds: 1 << 2,
  /** The source message for this crosspost has been deleted. */
  SourceMessageDeleted: 1 << 3,
  /** The message came from the urgent message system. */
  Urgent: 1 << 4,
  /** The message has an associated thread. */
  HasThread: 1 << 5,
  /** The message is visible only to its recipient. */
  Ephemeral: 1 << 6,
  /** The message is an interaction response still awaiting content. */
  Loading: 1 << 7,
  /** Some roles mentioned in a thread failed to be added. */
  FailedToMentionSomeRolesInThread: 1 << 8,
  /** Suppress push and desktop notifications for this message. */
  SuppressNotifications: 1 << 12,
  /** The message is a voice message. */
  IsVoiceMessage: 1 << 13,
  /**
   * The message uses the Components v2 layout system.
   *
   * @remarks
   * Setting this forbids `content` and `embeds` on the same message — the entire body
   * must be expressed as components. It cannot be unset once a message has been sent
   * with it.
   */
  IsComponentsV2: 1 << 15,
} as const

/**
 * A message flag.
 */
export type MessageFlags = (typeof MessageFlags)[keyof typeof MessageFlags]

/**
 * What a message reference points at.
 */
export const MessageReferenceType = {
  /** A reply, or a crosspost source. */
  Default: 0,
  /** A forwarded message, whose content is snapshotted rather than linked. */
  Forward: 1,
} as const

/**
 * A message reference type.
 */
export type MessageReferenceType = (typeof MessageReferenceType)[keyof typeof MessageReferenceType]

/**
 * Flags on a message attachment.
 */
export const AttachmentFlags = {
  /** The attachment is a clip of a stream. */
  IsRemix: 1 << 2,
} as const

/**
 * An attachment flag.
 */
export type AttachmentFlags = (typeof AttachmentFlags)[keyof typeof AttachmentFlags]

/**
 * The type of an embed.
 *
 * @remarks
 * Deprecated by Discord and retained only for parsing older messages. Do not branch
 * on it in new code.
 */
export const EmbedType = {
  /** Generic embed rendered from embed attributes. */
  Rich: 'rich',
  /** Image embed. */
  Image: 'image',
  /** Video embed. */
  Video: 'video',
  /** Animated gif image embed, rendered as a video. */
  GIFV: 'gifv',
  /** Article embed. */
  Article: 'article',
  /** Link embed. */
  Link: 'link',
  /** Poll result embed. */
  PollResult: 'poll_result',
} as const

/**
 * An embed type.
 */
export type EmbedType = (typeof EmbedType)[keyof typeof EmbedType]
